// SPDX-FileCopyrightText: 2026 Sprinkle <40203084+lnn0q@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Headphones;

[GenerateTypedNameReferences]
public sealed partial class HeadphoneMusicMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly AudioSystem _audioSystem;

    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;

    private EntityUid? _audio;
    private float _lockTimer;

    public HeadphoneMusicMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string song)
                return;

            OnSongSelected?.Invoke(song);
        };

        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        MusicList.Clear();

        foreach (var entry in jukeboxProtos)
        {
            MusicList.AddItem(entry.Name, metadata: entry.ID);
        }
    }

    public void SetSelectedSong(string name, float length)
    {
        SongName.Text = !string.IsNullOrEmpty(name) ? name : "---";
        PlaybackSlider.MaxValue = length;

        if (_audio == null || !_entManager.HasComponent<AudioComponent>(_audio.Value))
            PlaybackSlider.SetValueWithoutEvent(0);
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        if (_audio == null)
            return;

        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f || _audio == null;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = "00:00 / 00:00";
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        else
            PlaybackSlider.SetValueWithoutEvent(0f);
    }
}
