# SPDX-License-Identifier: AGPL-3.0-or-later

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  - Cluster
  - Cog
  - Delta
  - Elkridge
  - Kettle
  - Leonid
  - Loop
  - Marathon
  - OasisHighPop
  - Omega
  - Packed
  - Saltern
  - Snowball
  - Opticon
