using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Content.Shared.Paper;
using Content.Shared._BRatbite.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.RichText;
using Content.Client.UserInterface.RichText;
using Robust.Shared.Input;
using Robust.Client.UserInterface;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class DrawWindow : Container
{

    public List<PaperStroke> Strokes { get; set; } = new();
    public int MaxDrawingPoints { get; set; } = -1;
    private bool _drawing = false;
    public bool Drawing
    {
        get => _drawing;
        set
        {
            _drawing = value;
            MouseFilter = value ? MouseFilterMode.Stop : MouseFilterMode.Ignore;
        }
    }
    private bool _isMouseDown = false;

    public DrawWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        foreach (var stroke in Strokes)
        {
            Vector2 lastPoint = new();

            for (int i = 0; i < stroke.Points.Count; i++)
            {
                var point = stroke.Points[i];
                if (i != 0)
                    handle.DrawLine(lastPoint, point, stroke.Color);
                lastPoint = point;
            }
        }

        base.Draw(handle);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = true;

        // If the last stroke had at least one point, begin a new one
        if (Strokes.Count != 0 && Strokes[^1].Points.Count > 1)
        {
            Strokes.Add(new PaperStroke(new Color(0, 0, 0, 255)));
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick || !Drawing)
        {
            return;
        }

        _isMouseDown = false;
    }

    private int CountPoints(List<PaperStroke> strokes)
    {
        int count = 0;
        foreach (var stroke in strokes)
        {
            count += stroke.Points.Count;
        }
        return count;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        if (Drawing && _isMouseDown)
        {
            if (CountPoints(Strokes) >= MaxDrawingPoints)
            {
                return;
            }

            if (Strokes.Count == 0)
            {
                Strokes.Add(new PaperStroke(new Color(0, 0, 0, 255)));
            }
            Strokes[^1].AddPoint(args.RelativePosition);
        }
    }
}
