# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job # goob edit
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  goobcoins: 5 #Goob content    # Ratbite - why did tiders get 20 GC but bartenders 10? lowered
  access:
  - Maintenance
  special: # Goobstation
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - NanoTrasen
      - Assistant
    - type: CaptainSaberWeakness # Ratbite: Make captain saber deal more damage to passengers
      damageMultiplier: 1.2

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
