// SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Monolith Station contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitPreferenceSelector : Control
{
    private static readonly Color PositiveCostColor = Color.FromHex("#7bd88f");
    private static readonly Color NegativeCostColor = Color.FromHex("#ff8c8c");
    private static readonly Color NeutralCostColor = Color.Gray;
    private static readonly Color SelectedBackgroundColor = Color.FromHex("#3f4a3f");
    private static readonly Color SelectedTextColor = Color.FromHex("#d7ffd7");
    private static readonly Color UnavailableTextColor = Color.FromHex("#d46a6a");

    public int Cost;
    private bool _preference;
    private bool _unavailable;

    public bool Preference
    {
        get => _preference;
        set
        {
            _preference = value;
            UpdateButtonState();
        }
    }

    public event Action<bool>? PreferenceChanged;

    public TraitPreferenceSelector(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        Cost = trait.Cost;

        NameLabel.Text = Loc.GetString(trait.Name);

        var costText = "";
        if (trait.Cost > 0)
        {
            costText = $"-{trait.Cost}";
            CostLabel.FontColorOverride = NegativeCostColor;
        }
        else if (trait.Cost < 0)
        {
            costText = $"+{-trait.Cost}";
            CostLabel.FontColorOverride = PositiveCostColor;
        }
        else
        {
            costText = $"{trait.Cost}";
            CostLabel.FontColorOverride = NeutralCostColor;
        }

        CostLabel.Text = costText;

        TraitButton.OnPressed += OnTraitButtonPressed;

        if (trait.Description is { } desc)
            TraitButton.ToolTip = Loc.GetString(desc);

        UpdateButtonState();
    }

    public void SetTooltip(string tooltip)
    {
        TraitButton.TooltipSupplier = _ =>
        {
            var tip = new Robust.Client.UserInterface.CustomControls.Tooltip();
            tip.SetMessage(FormattedMessage.FromMarkupPermissive(tooltip));
            return tip;
        };
    }

    private void OnTraitButtonPressed(BaseButton.ButtonEventArgs args)
    {
        Preference = !Preference;
        PreferenceChanged?.Invoke(Preference);
    }

    private void UpdateButtonState()
    {
        SelectedLabel.Text = Preference ? ">" : "";
        TraitButton.Disabled = _unavailable;

        if (Preference)
        {
            TraitButton.ModulateSelfOverride = SelectedBackgroundColor;
            NameLabel.FontColorOverride = _unavailable ? UnavailableTextColor : SelectedTextColor;
        }
        else
        {
            TraitButton.StyleClasses.Add("OpenBottom");
            TraitButton.ModulateSelfOverride = null;
            NameLabel.FontColorOverride = _unavailable ? UnavailableTextColor : null;
        }
    }

    /// <summary>
    /// Sets the trait as unavailable for selection by coloring the name text red
    /// instead of coloring the entire button.
    /// </summary>
    /// <param name="unavailable">Whether the trait is unavailable for selection</param>
    public void SetUnavailable(bool unavailable)
    {
        _unavailable = unavailable;
        UpdateButtonState();
    }
}
